version: 2
updates:
  # Enable version updates for our CI github-actions.
  - package-ecosystem: "github-actions"
    # For GitHub Actions, setting the directory to / will check for workflow
    # files in .github/workflows.
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
