const { LitVocabTerm } = require('@lit/vocab-term')

/**
  Generated by artifact generator [], version []
  as part of artifact: [lit-generated-vocab-www.w3], version: [1.0.0]
  at ''.

  Vocabulary built from input: [./test/resources/vocabs/special-case-owl-snippet.ttl].
 */

const _NAMESPACE = "http://www.w3.org/2002/07/owl#";
function _NS (localName) { return (_NAMESPACE + localName) }

const OWL = {
  NAMESPACE: _NAMESPACE,
  NS: _NS,

    // *****************
    // All the Classes.
    // *****************

    /**
     * The class of collections of pairwise different individuals.
     */
    AllDifferent: new LitVocabTerm(_NS('AllDifferent'), localStorage, true)
      .addLabel('', `AllDifferent`)
      .addComment('', `The class of collections of pairwise different individuals.`),


  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}

module.exports = OWL;
