package com.inrupt.testing;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Namespace;
import org.eclipse.rdf4j.model.impl.SimpleNamespace;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

import com.inrupt.lit.vocab.LitVocab;
import com.inrupt.lit.vocab.LitVocabTerm;

/**
 * Generated by artifact generator [@lit/artifact-generator], version [0.1.0]
 * as part of artifact: [generated-vocab-common-TEST], version: [3.2.1-SNAPSHOT]
 * on 'Monday, November 18, 2019 3:51 PM'.
 *
 * Vocabulary built from vocab list file: [./test/resources/vocabs/vocab-list.yml].
 *
 * Vocabulary for terms used during Source Code Generation from RDF vocabularies.
 */
public class OVERRIDE_NAME implements LitVocab {
    public static final String PREFIX = "override-name";
    public static final String NAMESPACE = "https://w3id.org/lit/vocab/code-generation#";

    public static final IRI NAMESPACE_IRI = SimpleValueFactory.getInstance().createIRI("https://w3id.org/lit/vocab/code-generation#");
    public static final Namespace NS = new SimpleNamespace(PREFIX, NAMESPACE);

    @Override
    public final IRI getNamespaceIri() {
        return NAMESPACE_IRI;
    }

    private static String FULL_IRI(final String localName) {
        return NAMESPACE + localName;
    }

    // *****************
    // All the Classes.
    // *****************

    /**
     * This is a rdfs class.
     */
    public static final LitVocabTerm class1 = new LitVocabTerm(FULL_IRI("class1"), true)
      .addLabel("", "A rdfs class")
      .addComment("", "This is a rdfs class.");

    /**
     * This is an owl class.
     */
    public static final LitVocabTerm class2 = new LitVocabTerm(FULL_IRI("class2"), true)
      .addLabel("", "An owl class")
      .addComment("", "This is an owl class.");

    /**
     * This is a skos concept class.
     */
    public static final LitVocabTerm class3 = new LitVocabTerm(FULL_IRI("class3"), true)
      .addLabel("", "A skos concept class")
      .addComment("", "This is a skos concept class.");

    /**
     * This is a schema payment status type class.
     */
    public static final LitVocabTerm class4 = new LitVocabTerm(FULL_IRI("class4"), true)
      .addLabel("", "A schema payment status type class")
      .addComment("", "This is a schema payment status type class.");

    // *******************
    // All the Properties.
    // *******************

    /**
     * This is a rdf property.
     */
    public static final LitVocabTerm property1 = new LitVocabTerm(FULL_IRI("property1"), true)
      .addLabel("", "A rdf property")
      .addComment("", "This is a rdf property.");

    /**
     * This is a data type property.
     */
    public static final LitVocabTerm property2 = new LitVocabTerm(FULL_IRI("property2"), true)
      .addLabel("", "A rdfs data type property")
      .addComment("", "This is a data type property.");

    /**
     * This is an owl object property.
     */
    public static final LitVocabTerm property3 = new LitVocabTerm(FULL_IRI("property3"), true)
      .addLabel("", "An owl object property")
      .addComment("", "This is an owl object property.");

    /**
     * This is an owl named individual property.
     */
    public static final LitVocabTerm property4 = new LitVocabTerm(FULL_IRI("property4"), true)
      .addLabel("", "An owl named individual property")
      .addComment("", "This is an owl named individual property.");

    /**
     * This is an owl annotation property.
     */
    public static final LitVocabTerm property5 = new LitVocabTerm(FULL_IRI("property5"), true)
      .addLabel("", "An owl annotation property")
      .addComment("", "This is an owl annotation property.");

    /**
     * This is an owl datatype property.
     */
    public static final LitVocabTerm property6 = new LitVocabTerm(FULL_IRI("property6"), true)
      .addLabel("", "An owl datatype property")
      .addComment("", "This is an owl datatype property.");

    // *******************
    // All the Literals.
    // *******************

    /**
     * This is a rdfs literal.
     */
    public static final LitVocabTerm literal1 = new LitVocabTerm(FULL_IRI("literal1"), true)
      .addLabel("", "A rdfs literal")
      .addComment("", "This is a rdfs literal.");

    /**
     * Welcome
     */
    public static final LitVocabTerm literal2 = new LitVocabTerm(FULL_IRI("literal2"), true)
      .addMessage("en", "Welcome")
      .addMessage("es", "Bienvenido")
      .addMessage("fr", "Bienvenue");
}
