/**
 * Generated by the artifact generator [@inrupt/artifact-generator], version [2.0.0]
 * as part of artifact: [@inrupt/generated-vocab-schema], version: [1.0.0]
 * on 'Thursday, November 24, 2022 10:25 PM'.
 *
 * Vocabulary built from input: [./test/resources/vocab/schema-snippet.ttl].
 * The generator detected the following terms in the source vocabulary:
 *  - Classes: [1]
 *  - Properties: [3]
 *  - Literals: [0]
 *  - Constant IRIs: [0]
 *  - Constant strings: [0]
 *
 * Vocab needs a description.
 *
 * Namespace IRI: [https://schema.org/]
 */

// We prefix our local variables with underscores to (hopefully!) prevent
// potential names clashes with terms from vocabularies.
const _NAMESPACE = "https://schema.org/";
function _NS (localName) {
  return (_NAMESPACE + localName);
}

/**
 * Vocab needs a description.
 *
 * Namespace IRI: [https://schema.org/]
 */
const SCHEMA = {
  PREFIX: "schema",
  NAMESPACE: _NAMESPACE,
  PREFIX_AND_NAMESPACE: { "schema": "https://schema.org/" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * A person (alive, dead, undead, or fictional).
   *
   * This term provides descriptions only with no explicit locale.
   */
  Person: _NS("Person"),


  // *******************
  // All the Properties.
  // *******************

  /**
   * Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
   *
   * This term provides descriptions only with no explicit locale.
   */
  givenName: _NS("givenName"),

  /**
   * Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
   *
   * This term provides descriptions only with no explicit locale.
   */
  familyName: _NS("familyName"),

  /**
   * The country. For example, USA. You can also provide the two-letter <a href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166-1 alpha-2 country code</a>.
   *
   * This term provides descriptions only with no explicit locale.
   */
  addressCountry: _NS("addressCountry"),

}

module.exports = SCHEMA;
