/**
 * Generated by the artifact generator [@inrupt/artifact-generator], version [0.12.4]
 * as part of artifact: [@inrupt/generated-vocab-schema], version: [1.0.0]
 * on 'Friday, January 8, 2021 12:12 PM'.
 *
 * Vocabulary built from input: [./test/resources/vocabs/schema-snippet.ttl].
 */

const { VocabTerm, getLocalStore } = require("@inrupt/solid-common-vocab");
const DataFactory = require("@rdfjs/data-model");

const { namedNode } = DataFactory;

function _NS(localName) {
  return namedNode(`http://schema.org/${localName}`);
}

/**
 * [Generator provided] - undefined
 */
const SCHEMA = {
  PREFIX: "schema",
  NAMESPACE: "http://schema.org/",
  PREFIX_AND_NAMESPACE: { "schema": "http://schema.org/" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * A person (alive, dead, undead, or fictional).
   */
  Person: new VocabTerm(
    _NS("Person"),
    DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`Person`)
    .addCommentNoLanguage(`A person (alive, dead, undead, or fictional).`),


  // *******************
  // All the Properties.
  // *******************

  /**
   * Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
   */
  givenName: new VocabTerm(
    _NS("givenName"),
    DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`givenName`)
    .addCommentNoLanguage(`Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.`),

  /**
   * Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
   */
  familyName: new VocabTerm(
    _NS("familyName"),
    DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`familyName`)
    .addCommentNoLanguage(`Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.`),

  /**
   * The country. For example, USA. You can also provide the two-letter <a href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166-1 alpha-2 country code</a>.
   */
  addressCountry: new VocabTerm(
    _NS("addressCountry"),
    DataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`addressCountry`)
    .addCommentNoLanguage(`The country. For example, USA. You can also provide the two-letter <a href="http://en.wikipedia.org/wiki/ISO_3166-1">ISO 3166-1 alpha-2 country code</a>.`),

  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: "End of vocab."
}

module.exports = SCHEMA;
