/**
 * Generated by the artifact generator [@inrupt/artifact-generator], version [0.13.3]
 * as part of artifact: [generated-vocab-common-TEST], version: [3.2.1-SNAPSHOT]
 * on 'Monday, March 8, 2021 12:58 AM'.
 *
 * Vocabulary built from vocab list file: [./test/resources/vocabs/vocab-list.yml].
 */
package com.inrupt.testing;

import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.Namespace;
import org.eclipse.rdf4j.model.impl.SimpleNamespace;
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;

import org.solid.common.vocab.Vocab;
import org.solid.common.vocab.VocabTerm;
import com.inrupt.solid.common.vocab.VocabTermImpl;

/**
 * Inrupt extension to Schema.org terms providing
 multilingual alternative names (i.e. labels) and translations for comments
 (e.g. for use directly as labels or tool-tips in user interfaces or error
 messages). This extension very deliberately cherry-picks the individual terms
 from Schema.org that Inrupt currently deem generally useful for Solid and Solid
 applications (meaning we can provide a much cleaner, less noisy and smaller
 bundle size when generating programming language artifacts that provide
 convenient constants for just these selected terms, rather than including the
 over 2,500 terms currently defined in Schema.org).
 */
public class SCHEMA_INRUPT_EXT implements Vocab {
    public static final String PREFIX = "schema-inrupt-ext";
    public static final String NAMESPACE = "http://schema.org/";

    public static final IRI NAMESPACE_IRI = SimpleValueFactory.getInstance().createIRI("http://schema.org/");
    public static final Namespace NS = new SimpleNamespace(PREFIX, NAMESPACE);

    @Override
    public final String getNamespacePrefix() {
        return PREFIX;
    }

    @Override
    public final IRI getNamespaceIri() {
        return NAMESPACE_IRI;
    }

    private static String FULL_IRI(final String localName) {
        return NAMESPACE + localName;
    }

    // *****************
    // All the Classes.
    // *****************

    /**
     * A person (alive, dead, undead, or fictional).
     *
     * This term has [4] labels and comments, in the languages [de, es, fr, it].
     *
     * Defined by the vocabulary: https://w3id.org/inrupt/vocab/extension/schema#
     */
    public static final VocabTerm Person = new VocabTermImpl(FULL_IRI("Person"), true)
        .addIsDefinedBy(SimpleValueFactory.getInstance().createIRI("https://w3id.org/inrupt/vocab/extension/schema#"))
        .addLabel("Person", "en")
        .addLabel("La personne", "fr")
        .addLabel("Person", "de")
        .addLabel("Persona", "es")
        .addLabel("Persona", "it")
        .addLabelNoLanguage("Person")
        .addComment("Une personne (vivante, morte, mort-vivant ou fictive).", "fr")
        .addComment("Eine Person (lebendig, tot, untot oder fiktiv).", "de")
        .addComment("Una persona (viva, muerta, no muerta o ficticia).", "es")
        .addComment("Una persona (viva, morta, non morta o immaginaria).", "it")
        .addCommentNoLanguage("A person (alive, dead, undead, or fictional).");


    // *******************
    // All the Properties.
    // *******************

    /**
     * Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
     *
     * This term has [4] labels and comments, in the languages [de, es, fr, it].
     *
     * Defined by the vocabulary: https://w3id.org/inrupt/vocab/extension/schema#
     */
    public static final VocabTerm givenName = new VocabTermImpl(FULL_IRI("givenName"), true)
        .addIsDefinedBy(SimpleValueFactory.getInstance().createIRI("https://w3id.org/inrupt/vocab/extension/schema#"))
        .addLabel("Given Name", "en")
        .addLabel("Prénom", "fr")
        .addLabel("Vorname", "de")
        .addLabel("Nombre de pila", "es")
        .addLabel("Nome di battesimo", "it")
        .addLabelNoLanguage("givenName")
        .addComment("Prénom. Aux États-Unis, le prénom d’une personne. Ceci peut être utilisé avec familyName au lieu de la propriété name.", "fr")
        .addComment("Vorname. In den USA der Vorname einer Person. Dies kann zusammen mit familyName anstelle der Eigenschaft name verwendet werden.", "de")
        .addComment("Nombre de pila. En los EE. UU., El primer nombre de una persona. Esto se puede usar junto con familyName en lugar de la propiedad name.", "es")
        .addComment("Nome di battesimo. Negli Stati Uniti, il primo nome di una persona. Questo può essere usato insieme a familyName al posto della proprietà name.", "it")
        .addCommentNoLanguage("Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.");

    /**
     * Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
     *
     * This term has [4] labels and comments, in the languages [de, es, fr, it].
     *
     * Defined by the vocabulary: https://w3id.org/inrupt/vocab/extension/schema#
     */
    public static final VocabTerm familyName = new VocabTermImpl(FULL_IRI("familyName"), true)
        .addIsDefinedBy(SimpleValueFactory.getInstance().createIRI("https://w3id.org/inrupt/vocab/extension/schema#"))
        .addLabel("Family Name", "en")
        .addLabel("Nom de famille", "fr")
        .addLabel("Nachname", "de")
        .addLabel("Apellido", "es")
        .addLabel("Cognome", "it")
        .addLabelNoLanguage("familyName")
        .addComment("Nom de famille. Aux États-Unis, le nom de famille d’une personne. Ceci peut être utilisé avec GivenName au lieu de la propriété name.", "fr")
        .addComment("Nachname. In den USA der Nachname einer Person. Dies kann zusammen mit givenName anstelle der Eigenschaft name verwendet werden.", "de")
        .addComment("Apellido. En los EE.UU., el apellido de una persona. Esto se puede usar junto con givenName en lugar de la propiedad name.", "es")
        .addComment("Cognome. Negli Stati Uniti, il cognome di una persona. Questo può essere usato insieme a givenName al posto della proprietà name.", "it")
        .addCommentNoLanguage("Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.");
 }
