const { LitVocabTerm, getLocalStore } = require("@inrupt/lit-vocab-term");
const dataFactory = require("@rdfjs/data-model");

const { namedNode } = dataFactory;

/**
  Generated by artifact generator [@inrupt/lit-artifact-generator], version [0.10.12]
  as part of artifact: [generated-vocab-static-TEST], version: [10.11.12]
  at 'Tuesday, May 26, 2020 5:19 PM'.

  Vocabulary built from vocab list file: [test/resources/expectedOutputs/skipGeneration/vocab-list-no-publish.yml].

  Testing static file won't cause re-generation.
 */

function _NS(localName) {
  return namedNode(`https://inrupt.com/vocab/static-test-1#${localName}`);
}

const TEST_VOCAB_1 = {
  PREFIX: "test_vocab_1",
  NAMESPACE: "https://inrupt.com/vocab/static-test-1#",
  PREFIX_AND_NAMESPACE: { "test_vocab_1": "https://inrupt.com/vocab/static-test-1#" },
  NS: _NS,

  // *****************
  // All the Classes.
  // *****************

  /**
   * We have a label, but no comment!
   */
  sampleTerm: new LitVocabTerm(
    _NS("sampleTerm"),
    dataFactory,
    getLocalStore(),
    false
  )
    .addLabelNoLanguage(`We have a label, but no comment!`),


  //
  // Marker allowing us put commas at the end of all lines above (only the last line does not have a comma).
  //
  END_OF_VOCAB: 'End of vocab.'
}

module.exports = TEST_VOCAB_1;
